# Generated by Django 5.2.3 on 2026-05-06 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Washroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Engineering Block Washroom'", max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, help_text="Optional notes e.g. 'Ground floor, near main entrance'")),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from app without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostLocationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_from_nearest_node', models.FloatField(default=0)),
                ('nearest_node_name', models.CharField(blank=True, max_length=255)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('suggested_name', models.CharField(blank=True, help_text='Admin can fill this when approving', max_length=255)),
                ('admin_note', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_location_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Location Suggestion',
                'verbose_name_plural': 'Post Location Suggestions',
                'ordering': ['-occurrence_count', '-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('building', 'Building'), ('gate', 'Gate'), ('hostel', 'Hostel'), ('sport', 'Sports Facility'), ('atm', 'ATM'), ('park', 'Parking'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, help_text='Any extra details about this location')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Optional note from admin on approval/rejection')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_locations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggested Location',
                'verbose_name_plural': 'Suggested Locations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
